# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_passwordresetcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='FKqADlkZ5nzL1x4Z9oEv5FBxFHRAmok3idUtM0QZokOZhkEF', max_length=48),
        ),
    ]
