# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170122_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='aFLGQO8DyvsapBscilBtCN7ziY9QYnW1mJY31sYSwXySVdnd', max_length=48),
        ),
    ]
