# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170122_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='mdCjnKmC1YeA3cgVVJ75yp9gjTsvV1H5X8cV2FOxzgkotolj', max_length=48),
        ),
    ]
