# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170122_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='DTjREU45fVlqD0Fl2FFFaxrYfEmYXNdVJ3BewPh8tW5tHExp', max_length=48),
        ),
    ]
