# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170122_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=48),
        ),
    ]
